language: cpp
os: linux
sudo: required

branches:
  only: 
    - master
    - linux

matrix:
  fast_finish: true
  include:
    - name: gcc build
      compiler: gcc
      dist: focal
      env:
      - CC=gcc
      - CXX=g++
    - name: clang build
      compiler: clang
      dist: focal
      env:
      - CC=clang
      - CXX=clang++

before_install:
  - sudo apt update
  - sudo apt -y install libmfx1 libmfx-dev libmfx-tools libva-drm2 libva-x11-2 libva-glx2 libx11-dev libigfxcmrt7 libva-dev libdrm-dev libavcodec-extra libavcodec-dev libavutil-dev libavformat-dev libswresample-dev libavfilter-dev libass9 libass-dev
  - $CXX --version

script:
    - ./configure && make && ./qsvencc --version && python3 check_options.py
