language: cpp
os: linux
sudo: required

branches:
  only: 
    - master
    - linux

matrix:
  fast_finish: true
  include:
    - name: gcc build
      compiler: gcc
      dist: bionic
      env:
      - CC=gcc
      - CXX=g++
    - name: clang build
      compiler: clang
      dist: bionic
      env:
      - CC=clang-8
      - CXX=clang++-8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
          packages:
            - *native_deps
            - clang-8
            - clang++-8

before_install:
  - sudo -E add-apt-repository -y "ppa:jonathonf/ffmpeg-4"
  - sudo apt update
  - sudo apt -y install yasm nasm libavcodec-extra58 libavcodec-dev libavutil56 libavutil-dev libavformat58 libavformat-dev libswresample3 libswresample-dev libavfilter-extra7 libavfilter-dev libass9 libass-dev
  - $CXX --version

script:
    - ./configure && make && ./qsvencc --version
